version: '3'
services:
  server-app:
    image: server-app
    networks:
      - my-network
    ports:
      - "5050:80"

  main-app:
    image: main-app
    networks:
      - my-network
    depends_on:
      - server-app
    environment:
      - SERVER_ADDRESS = server  # Server "IP" that client connects to
    volumes:
      - shared-data:/data # Map the shared volume to /data in the client container
    
networks:
  my-network:
    driver: bridge

volumes:
  shared-data:  


# Docker pull server-app and main-app
# Then use command docker-compose up --build
